version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql-magento
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento2-ce
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - magento-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch-magento
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - magento-network

  opensearch:
    image: opensearchproject/opensearch:2.5.0
    container_name: opensearch-magento
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - plugins.security.disabled=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
    ports:
      - "9201:9200"
      - "9600:9600"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    networks:
      - magento-network

  redis:
    image: redis:7.0-alpine
    container_name: redis-magento
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - magento-network

  php-fpm:
    build:
      context: ./docker/php-fpm
    container_name: php-fpm-magento
    restart: unless-stopped
    volumes:
      - ./:/var/www/html:cached
    working_dir: /var/www/html
    networks:
      - magento-network
    depends_on:
      - mysql
      - redis

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-magento
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - magento-network

  nginx:
    image: nginx:1.27.3
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html:cached
      - ./local-services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php-fpm
      - elasticsearch
    networks:
      - magento-network

volumes:
  mysql_data:
    driver: local
  elasticsearch_data:
    driver: local
  opensearch_data:
    driver: local
  redis_data:
    driver: local

networks:
  magento-network:
    driver: bridge